variable "region" {}
variable "bucket_name" {}
variable "db_engine" {}
variable "db_instance_identifier" {}
variable "db_username" {}
variable "db_password" {}
variable "db_name" {}
variable "dynamodb_table_name" {}
variable "ami_id" {}
variable "ssh-key-name" {}